notime:
  # 是否启用
  enable: true
  # 白名单-时限内可进入且不会被踢出(请更改此处，默认为作者的ID)
  whitelist:
    - "Polang_"
  # 起始时间
  start: "00:00"
  # 结束时间
  end: "07:00"
  # 进不去时间段的提示
  kick-message: "&c[防沉迷] &b%start% &f至 &b%end% &f时间段内不能进入"
  # 时限开始时是否踢出已在线玩家
  kick-old: true
  # 反选，仅限定时间内可进入
  opposite: false

# 自定义时间命令
run:
  "1":
    enable: false # 是否启用
    time:
      - "00:10" # 时间可以为List列表
      - "00:20" # 如果为列表则command对应的是每个时间执行对应的行
    command: # 默认为后台执行
      - "对应时间 00:10 执行的命令;执行的命令2" # 可以使用 ; 符号来执行多命令
      - "对应时间 00:20 执行的命令"

  "2":
    enable: true
    time: "00:00:10" # 时间支持秒数！
    command:
      - "@m &7不早啦,是时候该睡觉觉咯~"
      - "命令2" # 如果时间不是列表那么将允许多行命令
      - "命令3"

  "stop": # 这是一个自动重启且对玩家提示的例子！
    enable: false # 是否启用
    time: # 时间列表
      - "02:50"
      - "02:55"
      - "02:59"
      - "02:59:50"
      - "02:59:55"
      - "02:59:56"
      - "02:59:57"
      - "02:59:58"
      - "02:59:59"
      - "03:00:00"
    command: # 后台执行
      - "@m &c服务器将在 &310分钟 &c后重启哦." # 如果为@m则表示给全部在线玩家发消息
      - "@m &c服务器将在 &35分钟 &c后重启哦."
      - "@m &c服务器将在 &31分钟 &c后重启啦."
      - "@m &c服务器在 &b10秒 &c后将会重启啦！"
      - "@m &c服务器在 &b5秒 &c后将会重启！！"
      - "@m &c服务器在 &b4秒 &c后将会重启！！"
      - "@m &c服务器在 &b3秒 &c后将会重启！！"
      - "@m &c服务器在 &b2秒 &c后将会重启！！！"
      - "@m &c服务器在 &b1秒 &c后将会重启！！！"
        #如果为 @k 则等于踢出所有在线玩家
      - "@k &c服务器正在重启;@s" #如果为 @s 则等于关闭服务器!!

  "周一": # 这是一个配合 PlayerTop 的每周排行榜与奖励的例子
    enable: false
    time: "01:00"
    command:
      # week=后面可以为星期一、星期二...星期日,也可以为数字1-7.
      # @papi 为开头将无视papi变量的解析，若没有这行则默认为解析papi变量.(有些插件命令会需要纯文本,有%变量%会导致直接解析)
      - "week=1;give %playerTop_{变量无需%%}_1_name% apple;@papi playertop delete %变量%;@m &a周排行榜已刷新！"

  "周二":
    enable: false
    time: "12:30"
    command:
      # week=周，你可以用英文也可以用中文
      - "周=1;@m &e又到了每周一，免费的午餐已发放~"
      - "week=1;@all give @name@ cooked_chicken"
  "每月任务":
    enable: false
    time: "12:30"
    command:
      # 表示每月的1号执行
      - "月=1;@m &e又到了每月的1号，免费的午餐已发放~"
      - "月=1;@all give @name@ cooked_chicken"

  "自动公告":
    enable: false # 是否启用
    fortime: "10m" # s=秒、m=分钟、h=小时、d=日.
    command:
      - "@m &a服务器群: 114514"
      - "@m &dmcbbs有你更精彩~"

  "在线玩家":
    enable: false # 是否启用
    time: "12:30"
    command:
      - "@m &e中午到啦,免费的午餐已发放~"
      - "@all give @name@ cooked_chicken"
  "定时扫地":
    enable: false # 是否启用
    time: "12:30"
    command:
      - "@m &e中午到啦,免费的午餐已发放~"
      - "@all give @name@ cooked_chicken"

# 插件启动时输入的命令&重启后执行的命令
startcommand:
  enable: false # 是否启用
  commands:
    - "say 开服执行命令1"
    - "say 开服执行命令2"